site_name: LinAlgZero
repo_url: https://github.com/atomwalk12/LinAlgZero
site_url: https://atomwalk12.github.io/LinAlgZero
site_description: This repository offers tools for generating a linear algebra problem dataset and training an open-source base model, aiming to explore its potential for emergent reasoning as inspired by the Deepseek-R1 paper.
site_author: Razvan Florian Vasile
edit_uri: edit/main/docs/
repo_name: atomwalk12/LinAlgZero
copyright: Maintained by <a href="https://github.com/atomwalk12">atomwalk12</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["linalgzero"]
          options:
            show_source: false
            show_root_heading: true
            show_root_toc_entry: true
            show_object_full_path: false
            show_root_full_path: false
            show_category_heading: true # Prints the category name (i.e. Functions, Classes, etc.)
            group_by_category: true
            heading_level: 2
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: astral-light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: astral-dark
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/atomwalk12/LinAlgZero
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/LinAlgZero

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
