# Distillation Configuration - Debug Mode
# This file contains the configuration for the distillation pipeline

# Dataset parameters
hf_dataset: null
hf_dataset_config: null
hf_dataset_split: "train"

# Prompt parameters
prompt_column: "prompt"
prompt_template: "{{ instruction }}"

# Model parameters
model: "deepseek-ai/DeepSeek-R1-Distill-Llama-70B"
vllm_server_url: "http://localhost:8000/v1"

# Generation parameters
temperature: 0.7
top_p: 0.9
max_new_tokens: 8192
num_generations: 1

# Processing parameters
input_batch_size: 64
client_replicas: 1
timeout: 600
retries: 2

# Output parameters
hf_output_dataset: null
private: false
