# Distillation Configuration for llama.cpp inference

# Dataset parameters
hf_dataset: null
hf_dataset_config: null
hf_dataset_split: "train"

# Prompt parameters
prompt_column: "prompt"
prompt_template: "{{ instruction }}"

# Generation parameters
temperature: 0.7
top_p: 0.9
max_new_tokens: 8192
num_generations: 1

# Processing parameters
input_batch_size: 64
client_replicas: 1
timeout: 600
retries: 2

# Output parameters
hf_output_dataset: null
private: false

# Server parameters
# Make sure to choose the link path that contains "resolve"
model: "https://huggingface.co/Salesforce/Llama-xLAM-2-8b-fc-r-gguf/resolve/main/Llama-xLAM-2-8B-fc-r-Q4_K_M.gguf"
n_gpu_layers: 32
host: "0.0.0.0"
port: 8000
n_ctx: 2048
split_mode: 2
